# ===== Build stage =====
FROM node:20-alpine AS build
WORKDIR /app

# Устанавливаем зависимости
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci

# Копируем исходники и собираем
COPY frontend/ ./
# build-time аргумент для URL API
ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
RUN npm run build

# ===== Run stage =====
FROM nginx:1.27-alpine
# Конфиг для SPA
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
